version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:13

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/data/postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data: